[project]
name = "db-backup-utility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-storage-blob>=12.28.0",
    "boto3>=1.42.53",
    "cryptography>=46.0.5",
    "pymysql>=1.1.2",
    "tenacity>=9.1.4",
]
